"""Recreating migration

Revision ID: 562b4ee62cf6
Revises: 
Create Date: 2025-02-16 18:23:45.167503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562b4ee62cf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_company_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_group_code', sa.String(length=255), nullable=False),
    sa.Column('customer_group_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('zipcode', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_group_code')
    )
    op.create_table('customer_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_type', sa.String(length=255), nullable=False),
    sa.Column('cash_and_carry_percentage', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salesman',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_code', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person_name', sa.String(length=255), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=True),
    sa.Column('customer_type_id', sa.Integer(), nullable=True),
    sa.Column('company_name_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('payment_terms_id', sa.Integer(), nullable=True),
    sa.Column('customer_group_id', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Integer(), nullable=True),
    sa.Column('product_promotion_id', sa.Integer(), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_msa_include', sa.Boolean(), nullable=True),
    sa.Column('is_sales_tax_applicable', sa.Boolean(), nullable=True),
    sa.Column('send_email_on_invoice_creation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_name_id'], ['customer_company_name.id'], ),
    sa.ForeignKeyConstraint(['customer_group_id'], ['customer_group.id'], ),
    sa.ForeignKeyConstraint(['customer_type_id'], ['customer_type.id'], ),
    sa.ForeignKeyConstraint(['payment_terms_id'], ['payment_terms.id'], ),
    sa.ForeignKeyConstraint(['product_promotion_id'], ['product_promotion.id'], ),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_customer_code'), 'customer', ['customer_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_customer_code'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('salesman')
    op.drop_table('product_promotion')
    op.drop_table('pricing_model')
    op.drop_table('payment_terms')
    op.drop_table('customer_type')
    op.drop_table('customer_group')
    op.drop_table('customer_company_name')
    # ### end Alembic commands ###
